Py4JNetworkError: An error occurred while trying to connect to the Java server (127.0.0.1:32778)/questions/72861743/py4jnetworkerror-an-error-occurred-while-trying-to-connect-to-the-java-server72861743
