Standalone PDO instance gets connected but I get an auth error when passed to redbean/questions/72866981/standalone-pdo-instance-gets-connected-but-i-get-an-auth-error-when-passed-to-re72866981
