ValueError: Exception encountered when calling layer "conv2d_1" (type Conv2D)/questions/72872021/valueerror-exception-encountered-when-calling-layer-conv2d-1-type-conv2d72872021
